### ISSUE TITLE
New renderer desyncs position and rotation of faces on the display cube from their true positions and rotations in 2D space

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#11]
I still need to find a way to reproduce properly
[screencast-jackal-42.github.io-2022.11.18-09_26_50.webm](https://user-images.githubusercontent.com/77758464/202727670-e8b4343b-d7ee-46fc-a1f0-840726cf79d6.webm)

**Comment by Jackal-42** [comment]
I think I know why this is happening, and it is different from what it may first appear to be: The new renderer is placing the faces on the cube display in a different orientation than they are on the true 2D behind-the-scenes level. The new renderer is way more broken than I thought and I think I'm gonna have to recall it in the next patch.
