### ISSUE TITLE
"Trick" Levels

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#12]
I created this with the hollow tile.
`91ad3a5g12ac4ab2agbgbg9af4af3aefg4b75a/92ad2a5b125a/225a/225a/225a/225a`

**Comment by robtech21** [comment]
I have a new level concept: "Zero Gravity"

Example: `90ae4a!g!4a17ac2a!2ag!2a17a!2aa!5a75a/225a/225a/225a/225a/106a!3afa!2afda!3af15af89a`

**Comment by Jackal-42** [comment]
Is the intention that the player turns off the button and then falls through the flag? If so, the flag is meant to only work when the player is standing on a solid surface. It was suggested that we have a "floating flag" which abides by different rules, but for now either way works I suppose.

**Comment by Jackal-42** [comment]
Level Codes are now organized in the levels.md file for convenience
