### ISSUE TITLE
Box issues when falling from one gravity zone to another

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#22]
If you have a box that goes falls down into a gravity zone facing left, it will drag against the ground and then stop completely until the player pushes it

Sample level:
`11|{117a!l41ac4ab60a/{225a/{225a/{225a/{225a/]2a$f4af4a$f4af2a5b20a5b8a!rb4ab3a$!r6b54a!a9a$!a85a`

**Comment by Jackal-42** [comment]
v0.4.1 fix 10👌
