### ISSUE TITLE
Sprites still won't rotate (again)

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#4]
Same problem as in #2

**Comment by Jackal-42** [comment]
This issue does not seem to be occurring on my machine. Perhaps send screenshots and a more detailed description?

**Comment by robtech21** [comment]
> This issue does not seem to be occurring on my machine. Perhaps send screenshots and a more detailed description?
![Screenshot 2022-11-16 8 51 57 AM](https://user-images.githubusercontent.com/77758464/202198778-60eb0852-d8d1-48d8-afc9-fc3b54e49afc.png)

Placing blocks on an out-of-view area of the cube, playing, and going back to the editor causes this to happen

**Comment by Jackal-42** [comment]
Fixed in v0.2 fix 1 (hopefully)
