### ISSUE TITLE
Level Samples with Push Buttons

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#5]
`114abcaeaf5b10a5befada5b75a/225a/225a/225a/225a/113a2b3ab4a2b100a`

`75a6b4ab4ab4a10b12ac2a10b4ab4ab4a6b75a/225a/103a@a4a@a4a@a4a@a4a@aa5b2a@eab4ab4a6b27a@2a3a@a4a@a37a/225a/225a/100a5bf3a2f3a2fadaf5b100a`

**Comment by Jackal-42** [comment]
Great concepts! The first one had me stumped for a little bit, until I realized I could pound. Also, I think that these levels demonstrate the need for a freecam, as in the first one the player is unable to see where the goal is, and in the second the player is unable to see where the button is. I will go about implementing that at my earliest convenience. Neither are too complicated, but they (especially the first) demonstrate the versatility of certain game mechanics.

**Comment by Jackal-42** [comment]
Levels Codes are now contained in the levels.md file for convenience.
