### ISSUE TITLE
Ground pieces sticking out of the cube side

### ISSUE THREAD

**Issue by S-Satt** [Jackal-42/cube_puzzler#9]
When switching back to the editor after play mode it draws some ground pieces on the wrong plane. Drawing them as a flat bit sticking out from the cube. Edit: It is fine in either of the playmodes (L or P) just screwed up in the editor 

Level Code: 27a@a25a@2a3a@2a3a@2a8a@2a57a@2a3a@2a!d2a@2a3a@2a2a@2a8ac8a5ba@3ab4ab4ab4ab4ab2a@2a3a@2a8a!a2a5b/75ab4ab4ab4ab4ab81ab4ab4ab4ab4ab27a/225a/225a/225a/125a5b45a5b45a 

![image](https://user-images.githubusercontent.com/118392860/202539907-a41d3008-b89a-48d2-bfab-452d337d1934.png)

**Comment by S-Satt** [comment]
It is also fixed for each square that you mouse over. quite funky indeed

**Comment by robtech21** [comment]
#4 exists
